# ============================================================================
# ~/.zshrc — zenful zsh config (template from zenify-my-terminal skill)
# ----------------------------------------------------------------------------
# Generated by the zenify-my-terminal skill. Sections marked OPTIONAL can be
# removed if you opted out of those features. Sections marked PRESERVED need
# to be filled in with the user's existing PATH/integration lines.
# ============================================================================

# --- Homebrew env (DO NOT use `brew shellenv` — it costs ~1.7s per startup) -
if [[ -x /usr/local/bin/brew ]]; then
  # Intel Mac: /usr/local/bin is already on PATH via /etc/paths.
  export HOMEBREW_PREFIX="/usr/local"
  export HOMEBREW_CELLAR="/usr/local/Cellar"
  export HOMEBREW_REPOSITORY="/usr/local/Homebrew"
elif [[ -x /opt/homebrew/bin/brew ]]; then
  # Apple Silicon: must add /opt/homebrew/bin to PATH manually.
  export HOMEBREW_PREFIX="/opt/homebrew"
  export HOMEBREW_CELLAR="/opt/homebrew/Cellar"
  export HOMEBREW_REPOSITORY="/opt/homebrew"
  export PATH="/opt/homebrew/bin:/opt/homebrew/sbin:$PATH"
fi

# --- PRESERVED: PATH additions from the user's previous .zshrc --------------
# Insert here any lines that added flutter, fnm, herd, openjdk, antigravity,
# opencode, bun, gcloud SDK PATH (path.zsh.inc), $HOME/.local/bin, etc.
# Example:
#   export PATH="$PATH:$HOME/development/flutter/bin"
#   export BUN_INSTALL="$HOME/.bun"
#   export PATH="$BUN_INSTALL/bin:$PATH"

# --- zinit bootstrap (auto-install on first run) ----------------------------
ZINIT_HOME="${XDG_DATA_HOME:-${HOME}/.local/share}/zinit/zinit.git"
if [[ ! -d "$ZINIT_HOME" ]]; then
  mkdir -p "$(dirname $ZINIT_HOME)"
  git clone https://github.com/zdharma-continuum/zinit.git "$ZINIT_HOME"
fi
source "${ZINIT_HOME}/zinit.zsh"

# --- History ----------------------------------------------------------------
HISTSIZE=5000
SAVEHIST=5000
HISTFILE=$HOME/.zsh_history
setopt APPEND_HISTORY SHARE_HISTORY HIST_IGNORE_SPACE
setopt HIST_IGNORE_ALL_DUPS HIST_SAVE_NO_DUPS HIST_IGNORE_DUPS HIST_FIND_NO_DUPS

# --- Keybindings ------------------------------------------------------------
# emacs mode (Ctrl-A/E/B/F, Alt-B/F, etc).
# Ctrl-P/N: prefix-matched history search.
# Autosuggest accept uses zsh-autosuggestions defaults: Ctrl-F/→ accept char,
# Alt-F accept word, Ctrl-E/End accept whole.
bindkey -e
bindkey '^p' history-search-backward
bindkey '^n' history-search-forward

# --- fpath additions (must precede compinit) --------------------------------
# Example: fpath=($HOME/.docker/completions $fpath)

# --- Plugins via zinit (turbo mode — load AFTER first prompt) ---------------
# Order matters within the for-list: completions before fzf-tab,
# syntax-highlighting MUST be last. atinit on syntax-highlighting runs
# zicompinit (cached compinit) right before that plugin loads.
# Drop the OMZP::* lines you don't want. NEVER add OMZP::command-not-found
# on macOS — the homebrew/command-not-found tap is dead.
zinit wait lucid depth=1 for \
  OMZP::git \
  OMZP::sudo \
  OMZP::aws \
  OMZP::kubectl \
  zsh-users/zsh-completions \
  Aloxaf/fzf-tab \
  zsh-users/zsh-autosuggestions \
  atinit"ZINIT[COMPINIT_OPTS]=-C; zicompinit; zicdreplay" zsh-users/zsh-syntax-highlighting

# --- LS_COLORS (portable string — no coreutils install needed) --------------
export LS_COLORS='di=34:ln=35:so=32:pi=33:ex=31:bd=46;34:cd=43;34:su=41;30:sg=46;30:tw=42;30:ow=43;30'

# --- Completion styling -----------------------------------------------------
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'
zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}"
zstyle ':completion:*' menu no
zstyle ':fzf-tab:complete:cd:*' fzf-preview 'ls -G $realpath'
zstyle ':fzf-tab:complete:__zoxide_z:*' fzf-preview 'ls -G $realpath'

# --- Aliases ----------------------------------------------------------------
alias ls='ls -G'             # macOS BSD ls; --color is GNU and won't work

# --- Tool init --------------------------------------------------------------
# Pick ONE prompt. Comment out the other.
# Fast-track default = Oh My Posh + pure theme. Starship is the alternative.
eval "$(oh-my-posh init zsh --config $HOMEBREW_PREFIX/opt/oh-my-posh/themes/catppuccin.omp.json)"
# eval "$(starship init zsh)"

eval "$(zoxide init zsh)"

# fzf shell integration. fzf >= 0.48 supports `fzf --zsh`; older brew installs
# fall back to the legacy script paths.
if fzf --zsh >/dev/null 2>&1; then
  eval "$(fzf --zsh)"
else
  [[ -f $HOMEBREW_PREFIX/opt/fzf/shell/key-bindings.zsh ]] && source $HOMEBREW_PREFIX/opt/fzf/shell/key-bindings.zsh
  [[ -f $HOMEBREW_PREFIX/opt/fzf/shell/completion.zsh ]]   && source $HOMEBREW_PREFIX/opt/fzf/shell/completion.zsh
fi

# --- Project switcher (terminal-neutral, used by Ghostty/cmux/iTerm/etc) ---
# WezTerm has its own Cmd-P binding via wezterm.lua; this is the fallback.
proj() {
  local d
  d=$(ls ~/projects 2>/dev/null | fzf --height 40% --reverse --prompt='project> ') || return
  cd ~/projects/"$d"
}

# --- Claude Code agent-teams launcher --------------------------------------
# Claude Code's teammateMode="tmux" makes parallel teammates spawn as split
# panes, but only when $TMUX is set. This wrapper ensures we're inside tmux
# before launching, so the split-pane mode actually activates.
claude-team() {
  if [[ -n "$TMUX" ]]; then
    claude "$@"
  elif tmux has-session -t claude 2>/dev/null; then
    tmux attach-session -t claude
  else
    tmux new-session -s claude "claude $*"
  fi
}

# --- Screenshot paste workaround for Claude Code in WezTerm + tmux ---------
# Cmd+V image paste doesn't reach Claude Code reliably when running inside
# tmux + WezTerm (binary clipboard data gets stripped by the multiplexer
# layer). Workaround: save the clipboard image to a temp file, print the
# path, then paste the path into Claude's prompt. See
# references/image-paste-workaround.md for the full story.
imgpaste() {
  local file="/tmp/claude-screenshot-$(date +%s).png"
  if command -v pngpaste >/dev/null 2>&1; then
    pngpaste "$file" 2>/dev/null
  else
    /usr/bin/osascript <<APPLESCRIPT >/dev/null 2>&1
try
  set theData to (the clipboard as «class PNGf»)
  set theFile to (open for access POSIX file "$file" with write permission)
  write theData to theFile
  close access theFile
on error
  try
    close access POSIX file "$file"
  end try
end try
APPLESCRIPT
  fi
  if [[ -s "$file" ]]; then
    echo "$file"
  else
    echo "No image in clipboard. Take a screenshot first:" >&2
    echo "  Cmd-Ctrl-Shift-4   → select region, copies to clipboard" >&2
    echo "  Cmd-Ctrl-Shift-3   → full screen, copies to clipboard" >&2
    rm -f "$file" 2>/dev/null
    return 1
  fi
}

# --- PRESERVED: sync integrations from the user's previous .zshrc ----------
# Things that need to be available immediately (e.g. fnm runs on every cd):
#   command -v fnm >/dev/null 2>&1 && eval "$(fnm env --use-on-cd --shell zsh)"
#   [[ -f "$HOME/Downloads/google-cloud-sdk/path.zsh.inc" ]] && . "$HOME/Downloads/google-cloud-sdk/path.zsh.inc"

# --- PRESERVED: deferred completions (these are SLOW — defer via zinit wait)
# Completion sources that take >0.5s should NOT be sync. Defer them via the
# null-plugin pattern. The actual command (e.g. gcloud, bun, entire) works
# immediately because it's on PATH; only tab-completion is briefly missing.
# Example:
#   zinit wait lucid for \
#     has'gcloud' id-as'gcloud-completion' \
#       atinit"[[ -f $HOME/Downloads/google-cloud-sdk/completion.zsh.inc ]] && source $HOME/Downloads/google-cloud-sdk/completion.zsh.inc" \
#       zdharma-continuum/null \
#     has'bun' id-as'bun-completion' \
#       atinit"[[ -s $HOME/.bun/_bun ]] && source $HOME/.bun/_bun" \
#       zdharma-continuum/null
